#tells travis we need to use superuser privileges, for docker
sudo: required

#tells travis we need to use docker
services:
    - docker

#commands executed before running tests/actions
#MUST use port mapping, general port 80 does not play nice with curl on travis ci
before_install:
    - docker build -t webserver .
    - docker run --rm -d -p 8080:3000 webserver

#main commands for travis, will add test suite here eventually
#must curl port 8080, did not work when using just port 80
script: 
    - sleep 60
    - curl -4fv http://localhost:8080

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "a website"
  env: "a-website-env"
  bucket_name: "elasticbeanstalk-us-east-2-897424296515"
  bucket_path: "a website"
  on:
    branch: dockerless_static_hosting
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY