#tells travis we need to use superuser privileges, for docker
sudo: required

#main commands for travis, will add test suite here eventually
#must curl port 8080, did not work when using just port 80
script: 
    - curl -4fv http://localhost:8080 &> /dev/stdout

#deploy stage, new attempt to deploy to AWS s3
deploy:
    provider: s3
    region: "us-east-2"
    bucket: "a-website-by-rephlekt"
    skip_cleanup: true
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
